### ISSUE TITLE
"pip3 install -r requirements.txt" got "locale.Error: unsupported locale setting" error

### ISSUE THREAD

**Issue by tonyxia2016** [valiant1x/intense-vpn#1]
"pip3 install -r requirements.txt" got "locale.Error: unsupported locale setting" error
OS: Ubuntu Server 16

:~/intense-vpn$ pip3 install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by tonyxia2016** [comment]
This link helps me on this issue.
https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting

Run following commands

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales
It will solve this.

**Comment by valiant1x** [comment]
Thanks for sharing your issue and the resolution.

Closing because this is more of an environment issue than an issue with our repo.
